[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi==0.103.1",
    "pydantic>=2.10.6",
    "uvicorn==0.23.2",
]
